name: Terraform Apply Workflow

# This workflow can be triggered manually via the GitHub Actions UI
on:
    pull_request:
      types:
        - closed
      branches:
        - main
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.8.0  # Specify the Terraform version to install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    # Step 3: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 4: Format Terraform
    - name: Terraform Fmt
      run: terraform fmt

    # Step 5: Verify Terraform
    - name: Terraform Verify
      run: terraform verify

    # Step 6: Apply Terraform
    - name: Terraform Apply
      run: terraform apply -var-file=secret.tfvars --auto-approve